import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Contact from "@/components/Contact";
import CertificationsFooter from "@/components/CertificationsFooter";

const gothamRoundedBold = localFont({
  src: "/fonts/gothamrnd_bold.otf",
  variable: "--font-gotham-rounded-bold",
  weight: "700",
  style: "normal",
});

const gothamRoundedMedium = localFont({
  src: "/fonts/gothamrnd_medium.otf",
  variable: "--font-gotham-rounded-medium",
  weight: "500",
  style: "normal",
});

const gothamRoundedLight = localFont({
  src: "/fonts/gothamrnd_light.otf",
  variable: "--font-gotham-rounded-light",
  weight: "300",
  style: "normal",
});


const gothamRoundedBook = localFont({
  src: "/fonts/gothamrnd_book.otf",
  variable: "--font-gotham-rounded-book",
  weight: "400",
  style: "normal",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gothamRoundedBold.className} ${gothamRoundedMedium.className} ${gothamRoundedLight.className} ${gothamRoundedBook.className} `}
      >
        <NavBar />
        {children}
        <Contact />
        <CertificationsFooter />
      </body>
    </html>
  );
}
